# C Vs Python : Integer為例子
如果檢視Python3.4的原始碼(假設C語言的邏輯看python)
像是一個指向複合式C結構的指標

In [ ]:
strust _longobject{
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
}

一個integer包含4部分:
* ob_refcnt : 參考得計數，用來協助Python處裡記憶體的配置和解除
* ob_type : 變數型態的編碼
* ob_size : 用來指出接下來的資料成員之大小
* ob_digit : 用來儲存打算在Python變數中表示的實際整數值

Pyton 相對來說在儲存整數時多了一些額外的負擔

小節 : 
* C的整數是一個以位元組編碼的整數值在記憶體中位址的一個標籤
* Python整數是一個指標，指向記憶體中一個包含所有Python物件資訊，其中包含有放置整數值的那些位元組

總之，python跑得比C慢~~


# Python的List不僅僅是List

In [2]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L[0])

int

In [4]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
type(L2),type(L2[0])

(list, str)

In [8]:
# 可以建立異質的list，會有額外的成本
L3 = [True,"2",3.0,4]
[type(item) for item in L3],type(L3)

([bool, str, float, int], list)

# Python 固定型態陣列

In [9]:
# 'i' 設定內容為整數
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 之後小節統一引入numpy 為 np
# 有錯誤請安裝 pip install numpy
import numpy as np

# 從 Python List 中建立陣列

In [13]:
#注意自動轉型態，明確定義型態
np.array([3.14,1,2,3],dtype='float32')

array([3.14, 1.  , 2.  , 3.  ], dtype=float32)

In [42]:
x = np.array([1,3,4])
x[0] = 3.14 # 小數點後會切掉
x

array([3, 3, 4])

In [14]:
# 不像list，numpy陣列可設定多維陣列
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# 從無到有建立陣列

In [40]:
print( np.zeros(10,dtype=int) ) #創建0的陣列
print( np.ones(10,dtype=int) ) #創建1的陣列
print( np.full((3,5),3.14) ) # 創建3.14的陣列
print( np.arange(2,20,2) ) # 創建3.14的陣列
print( np.linspace(0,1,5) ) # 創建0到1之間平均分布
print( np.random.random((3,3)) ) # 建立0~1之間3x3
print( np.random.normal(0,1,(3,3))) # 平均0、標準差1、內容為常態分佈3x3
print( np.random.randint(0,10,(3,3))) # [0,10]的整數亂數
print( np.eye(3)) # 單位矩陣 3x3
print( np.empty(3,order='C') ) # 這些值會是原本就存在那些記憶體中的值，速度比較快

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[0.47411854 0.53122619 0.35268596]
 [0.99374779 0.60880839 0.55703299]
 [0.79451181 0.54202003 0.84624008]]
[[ 1.21872817  0.2749535   1.5411418 ]
 [ 0.68844548 -0.56249859 -0.40929751]
 [ 0.78595432  0.7449888  -0.47033895]]
[[0 1 7]
 [3 4 7]
 [2 9 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]
